"""add_secret_password_hash_to_servicecredential

Revision ID: b20bbe62572d
Revises: d0f6f100b0df
Create Date: 2026-05-09 00:39:55.341207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b20bbe62572d'
down_revision: Union[str, Sequence[str], None] = 'd0f6f100b0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicecredential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicecredential', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('secret')

    # ### end Alembic commands ###
