"""add_service_credential

Revision ID: d0f6f100b0df
Revises: 
Create Date: 2026-05-08 17:25:46.130639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0f6f100b0df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('recoring_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_table('loves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('recoring_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_table('reset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('recoring_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_table('servicecredential',
    sa.Column('service', sa.Enum('plex', 'lastfm', 'listenbrainz', name='servicename'), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plex_server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plex_server_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicecredential')
    op.drop_table('reset')
    op.drop_table('loves')
    op.drop_table('hates')
    # ### end Alembic commands ###
